
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/sample_logs.log

  - type: log
    enabled: true
    paths:
      - /var/log/syslog

output.logstash:
  hosts: ["logstash:5044"]
